### ISSUE TITLE
Problem in mcfa.input()

### ISSUE THREAD

**Issue by GHEM900** [flh3/mcfa#1]
Can you help me with this issue? 

> x <- mcfa.input("sid", raw)
Error in ms[, i] <- ave(dat2[, i], g) : 
  incorrect number of subscripts on matrix
In addition: There were 50 or more warnings (use warnings() to see the first 50)

**Comment by flh3** [comment]
Please provide a reproducable example and I will see (I don't really maintain that function anymore).

**Comment by GHEM900** [comment]
Thank you Francis for your quick reply!

I want to do a MCFA for a new translated questionnaire. I try to do it with your guideline in your paper.
I just wanted to start and, but I get this error everytime. So I did it with your dataset raw and it was the same problem.

My R- Code:
source('https://raw.githubusercontent.com/flh3/mcfa/main/02_syntax/mcfa2.R')

library(lavaan)

library(readxl)
Testdaten <- read_excel("C:/Users/Phili/OneDrive/Desktop/Lokale-Sicherung_Thesis/Testdaten.xlsx") #my dataset
raw <- read_excel("C:/Users/Phili/OneDrive/Desktop/Lokale-Sicherung_Thesis/raw.xlsx")

alpha(Testdaten) 
x <- mcfa.input("sid", Testdaten)

alpha(raw)
x <- mcfa.input("sid", raw)



[raw.xlsx](https://github.com/flh3/mcfa/files/11550569/raw.xlsx)

**Comment by GHEM900** [comment]
Thank you Francis for your quick reply!

I want to do an MCFA for a new translated questionnaire. I am trying to do it with your guide in your paper.
I just wanted to start and, but I get this error every time. So I did it with your raw dataset and it was the same problem.

My R- Code:
source('https://raw.githubusercontent.com/flh3/mcfa/main/02_syntax/mcfa2.R')

library(lavaan)

library(readxl)
Testdaten <- read_excel("C:/Users/Phili/OneDrive/Desktop/Lokale-Sicherung_Thesis/Testdaten.xlsx") #my dataset
raw <- read_excel("C:/Users/Phili/OneDrive/Desktop/Lokale-Sicherung_Thesis/raw.xlsx")

alpha(Testdaten)
x <- mcfa.input("sid", Testdaten)

alpha(raw)
x <- mcfa.input("sid", raw)

[raw.xlsx](https://github.com/flh3/mcfa/files/11550579/raw.xlsx)

Thanks for helping me!

**Comment by flh3** [comment]
I just tried it and it works. 

source("https://raw.githubusercontent.com/flh3/mcfa/main/02_syntax/mcfa2.R")
raw <- read.csv("https://raw.githubusercontent.com/flh3/pubdata/main/MLCFA/raw.csv")
x <- mcfa.input("sid", raw)
str(x)

Note that the raw data file I provided is a csv file, not an Excel file.
